# Generated by Django 4.2 on 2024-10-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="players",
            old_name="team",
            new_name="team_name",
        ),
    ]
