# Generated by Django 4.2 on 2024-10-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("publish_time", models.DateTimeField()),
                ("video_url", models.URLField()),
            ],
        ),
    ]
