# Generated by Django 4.2 on 2024-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamerecord",
            name="game_number",
        ),
        migrations.AddField(
            model_name="gamerecord",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
