# Generated by Django 4.2 on 2024-10-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                ("batter_hand", models.CharField(max_length=10)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("school", models.CharField(blank=True, max_length=100, null=True)),
                ("draft_info", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "active_years",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("active_team", models.CharField(blank=True, max_length=50, null=True)),
                ("profile_img", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
