# Generated by Django 4.2 on 2024-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_1",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_10",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_11",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_12",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_2",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_3",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_4",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_5",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_6",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_7",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_8",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="inning_9",
        ),
        migrations.AddField(
            model_name="gamerecord",
            name="inning_scores_team_1",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="gamerecord",
            name="inning_scores_team_2",
            field=models.JSONField(default=list),
        ),
    ]
