# Generated by Django 4.2 on 2024-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_date", models.CharField(max_length=8)),
                ("base_time", models.CharField(max_length=4)),
                ("location", models.CharField(max_length=50)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("wind_direction", models.CharField(max_length=10)),
                ("rain_status", models.CharField(max_length=10)),
                ("rain_probability", models.FloatField(blank=True, null=True)),
                ("sky_status", models.CharField(blank=True, max_length=10, null=True)),
                ("precipitation", models.FloatField(blank=True, null=True)),
                ("min_temperature", models.FloatField(blank=True, null=True)),
                ("max_temperature", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
