# Generated by Django 4.2 on 2024-10-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_remove_gamerecord_game_number_gamerecord_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportsNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField()),
                ("published_at", models.DateTimeField()),
                ("content", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
