# Generated by Django 4.2 on 2024-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_remove_gamerecord_inning_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamerecord",
            name="b_team_1",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="b_team_2",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="e_team_1",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="e_team_2",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="h_team_1",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="h_team_2",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="r_team_1",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="r_team_2",
        ),
        migrations.AddField(
            model_name="gamerecord",
            name="r_h_e_b_team_1",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="gamerecord",
            name="r_h_e_b_team_2",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
