# Generated by Django 4.2 on 2024-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_remove_playerrecord_team_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerrecord",
            name="team_logo_url",
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
