# Generated by Django 4.2 on 2024-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_teamranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("team_name", models.CharField(max_length=100)),
                ("games_played", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("draws", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("games_behind", models.FloatField()),
                ("win_rate", models.FloatField()),
                ("streak", models.CharField(max_length=10)),
                ("last_10_games", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Team Record",
                "verbose_name_plural": "Team Records",
                "ordering": ["rank"],
            },
        ),
        migrations.DeleteModel(
            name="TeamRanking",
        ),
    ]
