# Generated by Django 4.2 on 2024-10-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_teamrecord_delete_teamranking"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamRecord",
            new_name="TeamRank",
        ),
    ]
