# Generated by Django 4.2 on 2024-10-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatResponse",
        ),
    ]
