# Generated by Django 4.2 on 2024-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat/image/%Y/%m/%d/"
            ),
        ),
    ]
