# Generated by Django 4.2 on 2024-10-13 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatparticipant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="chat.chatroom",
            ),
        ),
    ]
