# Generated by Django 4.2 on 2024-09-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="free",
            name="free_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="free/image/%Y/%m/%d/"
            ),
        ),
    ]
