# Generated by Django 4.2 on 2024-10-19 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="live",
            name="live_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="live/image/%Y/%m/%d/"
            ),
            preserve_default=False,
        ),
    ]
