# Generated by Django 4.2 on 2024-09-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="free",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
