# Generated by Django 4.2 on 2024-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="free",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
