# Generated by Django 4.2 on 2024-09-28 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_list",
            field=models.ManyToManyField(
                related_name="followee_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
